use_frameworks!

platform :ios, '8.0'

target 'ZKNSafeKit_Example' do
  pod 'ZKNSafeKit', :path => '../'

  target 'ZKNSafeKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
